### ISSUE TITLE
Add clear button in Visit goal

### ISSUE THREAD

**Issue by lubna-git** [osama1998H/spms#30]
Hi,
Can you add a **clear button** to clear value of Achievement in each row of Target Breakdown and Productivity in visit goal.

**Comment by osama1998H** [comment]
@lubna-git 
### please be more informative next time and make sure to explain the case carefully

- position of the button(top, on form)
- what fields exactly should be reset
- what fields should not be reset
- when the button should appear after saving or before making the new document?

**edit your issue carefully with the list above so that we can reference it later int in the KPI and in change log updates** 

for e.x
Subject: Request for adding a clear button to clear values in Target Breakdown and Visit Goal

Description:

I would like to request a feature for the custom frappe app "SPMS" to add a clear button for each row in the "Target Breakdown" and "Visit Goal" sections. The clear button should allow users to clear the values in the "Achievement" column in the "Target Breakdown" section and the "Productivity" column in the "Visit Goal" section.

This would provide a convenient way for users to reset the values in these columns, without having to manually delete each value. It would also improve the usability of the app and make it easier for users to make updates and adjustments to the targets.

I hope this feature can be added in a future update. Thank you for your consideration.

have a good day
